### PR TITLE
innitial time travel feature

### PR DESCRIPTION
**Pull request by ericmoderbacher**
This is my first pull request so be gentle on me.  (i use svn at work) but please let me know if there is anything I should do differently.

This is a very fun application, so excited to contribute!

### CODE REVIEW

**Comment by ericmoderbacher** [comment]
Please note that i just opened up some issues in my branch that are not addressed.  They might be mild enough to go ahead and merge, your call.  Thanks!

**Review by sarweiler — CHANGES_REQUESTED** [review]
Awesome work! Thanks, Eric!

One minor thing: Could you create a `lib` sub-directory and move linkedlist.lua there (and include it in the script via `include("lib/linkedlist")`? That way linkedlist.lua will not show up in the Norns menu screen.

**Comment by sarweiler** [comment]
I just noticed you already have an issue for that in your fork. 👍

**Review by ericmoderbacher — COMMENTED** [review]
fixed lib issue

**Comment by ericmoderbacher** [comment]
Ok i think this is fixed.  New to git let me know if i messed this process up.  Thanks!

**Comment by sarweiler** [comment]
All great, thanks! Will merge now and create a new release.

**Pull request merged**
